ALTER TABLE hd_plt_risk ADD COLUMN risk_code VARCHAR(64);
ALTER TABLE hd_plt_risk ADD COLUMN study_code_snapshot VARCHAR(64);
ALTER TABLE hd_plt_risk ADD COLUMN program_id BIGINT;
ALTER TABLE hd_plt_risk ADD COLUMN program_code_snapshot VARCHAR(64);
ALTER TABLE hd_plt_risk ADD COLUMN project_id BIGINT;
ALTER TABLE hd_plt_risk ADD COLUMN project_code_snapshot VARCHAR(64);
ALTER TABLE hd_plt_risk ADD COLUMN function_line_id BIGINT;
ALTER TABLE hd_plt_risk ADD COLUMN function_line_code_snapshot VARCHAR(64);
ALTER TABLE hd_plt_risk ADD COLUMN function_line_name_snapshot VARCHAR(100);
ALTER TABLE hd_plt_risk ADD COLUMN owner_user_id BIGINT;
ALTER TABLE hd_plt_risk ADD COLUMN owner_email_snapshot VARCHAR(254);
ALTER TABLE hd_plt_risk ADD COLUMN owner_name_snapshot VARCHAR(100);
ALTER TABLE hd_plt_risk ADD COLUMN risk_description CLOB;
ALTER TABLE hd_plt_risk ADD COLUMN registered_date DATE;
ALTER TABLE hd_plt_risk ADD COLUMN status_code VARCHAR(20) DEFAULT 'OPEN';
ALTER TABLE hd_plt_risk ADD COLUMN closed_time TIMESTAMP(6);
ALTER TABLE hd_plt_risk ADD COLUMN close_reason CLOB;
ALTER TABLE hd_plt_risk ADD COLUMN latest_assessment_id BIGINT;
ALTER TABLE hd_plt_risk ADD COLUMN current_score INT;
ALTER TABLE hd_plt_risk ADD COLUMN current_level_code VARCHAR(20);
ALTER TABLE hd_plt_risk ADD COLUMN row_version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE hd_plt_risk ADD COLUMN sys_create_by VARCHAR(254) DEFAULT 'system';
ALTER TABLE hd_plt_risk ADD COLUMN sys_update_by VARCHAR(254) DEFAULT 'system';
ALTER TABLE hd_plt_risk ADD COLUMN sys_create_time TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE hd_plt_risk ADD COLUMN sys_update_time TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE hd_plt_risk ADD CONSTRAINT uk_hd_plt_risk_code UNIQUE(risk_code);

CREATE TABLE hd_plt_risk_rule_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_no INT NOT NULL UNIQUE,
    version_name VARCHAR(100) NOT NULL,
    low_risk_max_score INT NOT NULL,
    medium_risk_max_score INT NOT NULL,
    status_code VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    effective_from TIMESTAMP(6), effective_to TIMESTAMP(6),
    approved_by VARCHAR(254), approved_time TIMESTAMP(6),
    version_description VARCHAR(500),
    sys_create_by VARCHAR(254) NOT NULL, sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE hd_plt_risk_assessment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_id BIGINT NOT NULL, assessment_no INT NOT NULL, rule_version_id BIGINT NOT NULL,
    impact_score SMALLINT NOT NULL, likelihood_score SMALLINT NOT NULL,
    detectability_score SMALLINT NOT NULL, total_score INT NOT NULL,
    risk_level_code VARCHAR(20) NOT NULL, assessment_reason CLOB,
    assessed_by VARCHAR(254) NOT NULL, assessed_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_create_by VARCHAR(254) NOT NULL, sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0,
    UNIQUE(risk_id, assessment_no)
);

CREATE TABLE hd_plt_risk_action (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_id BIGINT NOT NULL, action_type_code VARCHAR(32) NOT NULL DEFAULT 'CONTROL',
    action_description CLOB NOT NULL, owner_user_id BIGINT NOT NULL,
    owner_email_snapshot VARCHAR(254) NOT NULL, owner_name_snapshot VARCHAR(100) NOT NULL,
    planned_date DATE, completed_date DATE,
    status_code VARCHAR(20) NOT NULL DEFAULT 'OPEN', completion_note CLOB,
    row_version BIGINT NOT NULL DEFAULT 0,
    sys_create_by VARCHAR(254) NOT NULL, sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0
);

INSERT INTO hd_plt_risk_rule_version(
    version_no, version_name, low_risk_max_score, medium_risk_max_score,
    status_code, effective_from, approved_by, approved_time,
    version_description, sys_create_by, sys_update_by)
VALUES (1, '风险评分规则 V1', 12, 36, 'ACTIVE', CURRENT_TIMESTAMP,
        'system', CURRENT_TIMESTAMP, 'PRD v1.0 默认阈值', 'system', 'system');

INSERT INTO hd_plt_permission(
    module_code, permission_code, permission_name, permission_type, action_code,
    status_code, sort_order, sys_create_by, sys_update_by)
VALUES
    ('risk', 'risk.page.view', '查看风险管理页面', 'PAGE', 'view', 'ACTIVE', 70, 'system', 'system'),
    ('risk', 'risk.read', '查询风险', 'DATA', 'read', 'ACTIVE', 71, 'system', 'system'),
    ('risk', 'risk.create', '新增风险', 'DATA', 'create', 'ACTIVE', 72, 'system', 'system'),
    ('risk', 'risk.update', '修改风险', 'DATA', 'update', 'ACTIVE', 73, 'system', 'system'),
    ('risk', 'risk.delete', '删除风险', 'DATA', 'delete', 'ACTIVE', 74, 'system', 'system');

INSERT INTO hd_plt_role_permission(role_id, permission_id, sys_create_by, sys_update_by)
SELECT r.id, p.id, 'system', 'system' FROM hd_plt_role r JOIN hd_plt_permission p ON
  p.permission_code IN ('risk.page.view','risk.read','risk.create','risk.update','risk.delete')
WHERE r.role_name = 'ADMIN';
INSERT INTO hd_plt_role_permission(role_id, permission_id, sys_create_by, sys_update_by)
SELECT r.id, p.id, 'system', 'system' FROM hd_plt_role r JOIN hd_plt_permission p ON
  p.permission_code IN ('risk.page.view','risk.read','risk.create','risk.update')
WHERE r.role_name = 'USER';
INSERT INTO hd_plt_role_permission(role_id, permission_id, sys_create_by, sys_update_by)
SELECT r.id, p.id, 'system', 'system' FROM hd_plt_role r JOIN hd_plt_permission p ON
  p.permission_code IN ('risk.page.view','risk.read')
WHERE r.role_name = 'VIEWER';
