-- 月报表结构回填：H2 V6 中的 hd_plt_monthly_report 只是 3 列桩表，
-- 这里按 mysql V1（post-V9，无 program_name_snapshot / project_name_snapshot）
-- 重建全列，并新建进展明细表 hd_plt_monthly_report_entry。
DROP TABLE hd_plt_monthly_report;

CREATE TABLE hd_plt_monthly_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT NOT NULL,
    report_month DATE NOT NULL,
    function_line_id BIGINT NOT NULL,
    function_line_code_snapshot VARCHAR(64) NOT NULL,
    function_line_name_snapshot VARCHAR(100) NOT NULL,
    study_code_snapshot VARCHAR(64) NOT NULL,
    program_code_snapshot VARCHAR(64) NOT NULL,
    product_name_snapshot VARCHAR(200) NOT NULL,
    project_code_snapshot VARCHAR(64) NOT NULL,
    therapeutic_area_code_snapshot VARCHAR(64) NOT NULL,
    therapeutic_area_name_snapshot VARCHAR(100) NOT NULL,
    indication_description_snapshot VARCHAR(500) NOT NULL,
    sys_create_by VARCHAR(254) NOT NULL,
    sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_hd_plt_monthly_report UNIQUE (study_id, report_month, function_line_id)
);

CREATE INDEX idx_hd_plt_monthly_report_month
    ON hd_plt_monthly_report (report_month, sys_deleted);
CREATE INDEX idx_hd_plt_monthly_report_study_month
    ON hd_plt_monthly_report (study_id, report_month, sys_deleted);
CREATE INDEX idx_hd_plt_monthly_report_function
    ON hd_plt_monthly_report (function_line_id, report_month, sys_deleted);

CREATE TABLE hd_plt_monthly_report_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monthly_report_id BIGINT NOT NULL,
    entry_date DATE NOT NULL,
    sequence_no INT NOT NULL DEFAULT 1,
    progress_content CLOB NOT NULL,
    sys_create_by VARCHAR(254) NOT NULL,
    sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_hd_plt_monthly_report_entry_order UNIQUE (monthly_report_id, sequence_no)
);

CREATE INDEX idx_hd_plt_monthly_report_entry_date
    ON hd_plt_monthly_report_entry (monthly_report_id, entry_date, sys_deleted);
