CREATE TABLE hd_plt_risk_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_id BIGINT NOT NULL,
    from_status VARCHAR(20) NOT NULL,
    to_status VARCHAR(20) NOT NULL,
    reason VARCHAR(2000) NOT NULL,
    changed_by VARCHAR(254) NOT NULL,
    changed_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_hd_plt_risk_status_history_risk
    ON hd_plt_risk_status_history (risk_id, changed_time);

CREATE TABLE hd_plt_risk_action_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_id BIGINT NOT NULL,
    risk_id BIGINT NOT NULL,
    change_type VARCHAR(20) NOT NULL,
    from_status VARCHAR(20),
    to_status VARCHAR(20),
    snapshot_json CLOB,
    reason VARCHAR(2000),
    changed_by VARCHAR(254) NOT NULL,
    changed_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_hd_plt_risk_action_history_risk
    ON hd_plt_risk_action_history (risk_id, changed_time);

CREATE INDEX idx_hd_plt_risk_action_history_action
    ON hd_plt_risk_action_history (action_id, changed_time);
