CREATE TABLE hd_plt_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    status_code VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    security_stamp CHAR(36) NOT NULL,
    sys_create_by VARCHAR(254) NOT NULL,
    sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE hd_plt_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(100) NOT NULL UNIQUE,
    role_description VARCHAR(500),
    data_scope_mode VARCHAR(32) NOT NULL DEFAULT 'ASSIGNED_STUDY',
    status_code VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    is_system_role SMALLINT NOT NULL DEFAULT 0,
    sys_create_by VARCHAR(254) NOT NULL,
    sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE hd_plt_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_code VARCHAR(64) NOT NULL,
    permission_code VARCHAR(128) NOT NULL UNIQUE,
    permission_name VARCHAR(100) NOT NULL,
    permission_type VARCHAR(20) NOT NULL,
    action_code VARCHAR(32) NOT NULL,
    permission_description VARCHAR(500),
    status_code VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    sort_order INT NOT NULL DEFAULT 0,
    sys_create_by VARCHAR(254) NOT NULL,
    sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE hd_plt_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    sys_create_by VARCHAR(254) NOT NULL,
    sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0,
    UNIQUE(user_id, role_id, sys_deleted)
);

CREATE TABLE hd_plt_role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    sys_create_by VARCHAR(254) NOT NULL,
    sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0,
    UNIQUE(role_id, permission_id)
);

CREATE TABLE hd_plt_system_setting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(100) NOT NULL UNIQUE,
    config_value CLOB NOT NULL,
    value_type VARCHAR(20) NOT NULL DEFAULT 'STRING',
    config_description VARCHAR(500),
    public_visible SMALLINT NOT NULL DEFAULT 0,
    sys_create_by VARCHAR(254) NOT NULL,
    sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE hd_plt_therapeutic_area (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_code VARCHAR(64) NOT NULL UNIQUE,
    area_name VARCHAR(100) NOT NULL,
    english_name VARCHAR(200),
    sort_order INT NOT NULL DEFAULT 0,
    status_code VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    sys_create_by VARCHAR(254) NOT NULL,
    sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE hd_plt_program (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_code VARCHAR(64) NOT NULL UNIQUE,
    program_name VARCHAR(200) NOT NULL,
    product_name VARCHAR(200) NOT NULL UNIQUE,
    moa VARCHAR(500),
    source_code VARCHAR(32),
    origin_code VARCHAR(32),
    status_code VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    sort_order INT NOT NULL DEFAULT 0,
    sys_create_by VARCHAR(254) NOT NULL,
    sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE hd_plt_project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code VARCHAR(64) NOT NULL UNIQUE,
    project_name VARCHAR(200) NOT NULL,
    program_id BIGINT NOT NULL,
    indication_description VARCHAR(500) NOT NULL,
    therapeutic_area_id BIGINT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    project_description CLOB,
    sys_create_by VARCHAR(254) NOT NULL,
    sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE hd_plt_study (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_code VARCHAR(64) NOT NULL UNIQUE,
    study_name VARCHAR(200) NOT NULL,
    phase_status_code VARCHAR(32),
    planned_start_date DATE,
    planned_end_date DATE,
    actual_start_date DATE,
    actual_end_date DATE,
    study_description CLOB,
    program_id BIGINT NOT NULL,
    program_code_snapshot VARCHAR(64) NOT NULL,
    program_name_snapshot VARCHAR(200) NOT NULL,
    product_name_snapshot VARCHAR(200) NOT NULL,
    moa_snapshot VARCHAR(500),
    source_code_snapshot VARCHAR(32),
    origin_code_snapshot VARCHAR(32),
    project_id BIGINT NOT NULL,
    project_code_snapshot VARCHAR(64) NOT NULL,
    project_name_snapshot VARCHAR(200) NOT NULL,
    therapeutic_area_id BIGINT NOT NULL,
    therapeutic_area_code_snapshot VARCHAR(64) NOT NULL,
    therapeutic_area_name_snapshot VARCHAR(100) NOT NULL,
    indication_description_snapshot VARCHAR(500) NOT NULL,
    sys_create_by VARCHAR(254) NOT NULL,
    sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE hd_plt_team_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT NOT NULL,
    team_role_id BIGINT NOT NULL DEFAULT 1,
    user_id BIGINT NOT NULL,
    team_role_code_snapshot VARCHAR(64) NOT NULL DEFAULT 'MEMBER',
    team_role_name_snapshot VARCHAR(100) NOT NULL DEFAULT 'Member',
    user_email_snapshot VARCHAR(254) NOT NULL DEFAULT 'member@example.com',
    user_name_snapshot VARCHAR(100) NOT NULL DEFAULT 'Member',
    sys_create_by VARCHAR(254) NOT NULL DEFAULT 'seed',
    sys_update_by VARCHAR(254) NOT NULL DEFAULT 'seed',
    sys_create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE hd_plt_spring_session (
    PRIMARY_ID CHAR(36) PRIMARY KEY,
    SESSION_ID CHAR(36) NOT NULL UNIQUE,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(254)
);

CREATE INDEX idx_hd_plt_spring_session_expiry ON hd_plt_spring_session(EXPIRY_TIME);
CREATE INDEX idx_hd_plt_spring_session_principal ON hd_plt_spring_session(PRINCIPAL_NAME);

CREATE TABLE hd_plt_spring_session_attributes (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BINARY LARGE OBJECT NOT NULL,
    PRIMARY KEY(SESSION_PRIMARY_ID, ATTRIBUTE_NAME)
);
