CREATE TABLE hd_plt_project_milestone (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    stage_code VARCHAR(64) NOT NULL,
    milestone_code VARCHAR(100) NOT NULL,
    plan_v1_date DATE,
    plan_v2_date DATE,
    actual_start_date DATE,
    actual_end_date DATE,
    deviation_note CLOB,
    sys_create_by VARCHAR(254) NOT NULL,
    sys_update_by VARCHAR(254) NOT NULL,
    sys_create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sys_deleted SMALLINT NOT NULL DEFAULT 0,
    UNIQUE(project_id, milestone_code, sys_deleted)
);

CREATE INDEX idx_hd_plt_project_milestone_stage ON hd_plt_project_milestone(project_id, stage_code, sys_deleted);

-- 项目监管里程碑权限
INSERT INTO hd_plt_permission(
    module_code, permission_code, permission_name, permission_type, action_code,
    status_code, sort_order, sys_create_by, sys_update_by)
VALUES
    ('milestone', 'project.milestone.read', '查看项目监管里程碑', 'DATA', 'read', 'ACTIVE', 90, 'system', 'system'),
    ('milestone', 'project.milestone.update', '修改项目监管里程碑', 'DATA', 'update', 'ACTIVE', 100, 'system', 'system');

INSERT INTO hd_plt_role_permission(role_id, permission_id, sys_create_by, sys_update_by)
SELECT r.id, p.id, 'system', 'system' FROM hd_plt_role r JOIN hd_plt_permission p ON
  p.permission_code = 'project.milestone.read'
WHERE r.role_name IN ('ADMIN', 'USER');

INSERT INTO hd_plt_role_permission(role_id, permission_id, sys_create_by, sys_update_by)
SELECT r.id, p.id, 'system', 'system' FROM hd_plt_role r JOIN hd_plt_permission p ON
  p.permission_code = 'project.milestone.update'
WHERE r.role_name IN ('ADMIN', 'USER');
