CREATE TABLE hd_plt_study_milestone (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT NOT NULL,
    sys_deleted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE hd_plt_monthly_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT NOT NULL,
    sys_deleted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE hd_plt_risk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT NOT NULL,
    sys_deleted SMALLINT NOT NULL DEFAULT 0
);

INSERT INTO hd_plt_permission(
    module_code, permission_code, permission_name, permission_type, action_code,
    status_code, sort_order, sys_create_by, sys_update_by)
VALUES
    ('config', 'config.page.view', 'View pipeline configuration', 'PAGE', 'view', 'ACTIVE', 29, 'system', 'system'),
    ('config', 'config.update', 'Update pipeline configuration', 'OPERATION', 'update', 'ACTIVE', 31, 'system', 'system'),
    ('config', 'config.delete', 'Delete pipeline configuration', 'OPERATION', 'delete', 'ACTIVE', 32, 'system', 'system');

INSERT INTO hd_plt_role_permission(role_id, permission_id, sys_create_by, sys_update_by)
SELECT r.id, p.id, 'system', 'system'
FROM hd_plt_role r
JOIN hd_plt_permission p ON p.permission_code IN (
    'config.page.view', 'config.update', 'config.delete')
WHERE r.role_name = 'ADMIN' AND r.sys_deleted = 0 AND p.sys_deleted = 0;

DELETE FROM hd_plt_role_permission
WHERE role_id IN (SELECT id FROM hd_plt_role WHERE role_name = 'USER')
  AND permission_id IN (SELECT id FROM hd_plt_permission WHERE permission_code = 'config.create');

DELETE FROM hd_plt_spring_session_attributes;
DELETE FROM hd_plt_spring_session;
