-- 管线总览演示数据：覆盖 6 个治疗领域（TA）的 Program / Project / Study。
-- 仅在库为空或演示环境使用；生产数据应由业务功能线维护。
-- 注意 V9 已删除 program_name / project_name / study_name 及对应快照列，本文件只写入存活列。
-- FK 通过子查询按业务编码引用，避免硬编码自增主键。

-- 1) Program（项目集 / 产品）
-- 幂等：若 program_code 或 product_name 已存在则更新，避免重复键报错（演示库可能已含同源数据）。
INSERT INTO hd_plt_program (
    program_code, product_name, moa, source_code, origin_code,
    status_code, sort_order, sys_create_by, sys_update_by)
VALUES
    ('PRG-ONC-ADC', 'HDM2001', 'ADC', 'SELF_DEVELOPED', 'DOMESTIC', 'ACTIVE', 10, 'seed', 'seed'),
    ('PRG-AUTO-MAB', 'HDM3002', 'Monoclonal Antibody', 'IN_LICENSE', 'IMPORTED', 'ACTIVE', 20, 'seed', 'seed'),
    ('PRG-MET-PEP', 'HDM1005', 'Peptide', 'SELF_DEVELOPED', 'DOMESTIC', 'ACTIVE', 30, 'seed', 'seed'),
    ('PRG-RES-INH', 'HDM4003', 'Small Molecule', 'COOPERATION', 'DOMESTIC', 'ACTIVE', 40, 'seed', 'seed'),
    ('PRG-INF-VAX', 'HDM5001', 'Vaccine', 'SELF_DEVELOPED', 'DOMESTIC', 'ACTIVE', 50, 'seed', 'seed'),
    ('PRG-NEU-ASO', 'HDM6001', 'Antisense Oligonucleotide', 'IN_LICENSE', 'IMPORTED', 'ACTIVE', 60, 'seed', 'seed')
ON DUPLICATE KEY UPDATE
    product_name   = VALUES(product_name),
    moa            = VALUES(moa),
    source_code    = VALUES(source_code),
    origin_code    = VALUES(origin_code),
    status_code    = VALUES(status_code),
    sort_order     = VALUES(sort_order),
    sys_update_by  = VALUES(sys_update_by);

-- 2) Project（项目），按 TA 聚合展示；肿瘤放 2 个以体现同 TA 多项目
-- 幂等：若 project_code 已存在则更新。
INSERT INTO hd_plt_project (
    project_code, program_id, indication_description, therapeutic_area_id,
    sort_order, sys_create_by, sys_update_by)
VALUES
    ('PJ-ONC-ADC-01',
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-ONC-ADC'),
        '晚期实体瘤',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'ONCOLOGY'),
        10, 'seed', 'seed'),
    ('PJ-ONC-ADC-02',
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-ONC-ADC'),
        '三阴性乳腺癌',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'ONCOLOGY'),
        20, 'seed', 'seed'),
    ('PJ-AUTO-MAB-01',
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-AUTO-MAB'),
        '系统性红斑狼疮',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'AUTOIMMUNE'),
        10, 'seed', 'seed'),
    ('PJ-MET-PEP-01',
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-MET-PEP'),
        '2 型糖尿病',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'METABOLIC_CARDIOVASCULAR'),
        10, 'seed', 'seed'),
    ('PJ-RES-INH-01',
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-RES-INH'),
        '慢性阻塞性肺疾病',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'RESPIRATORY'),
        10, 'seed', 'seed'),
    ('PJ-INF-VAX-01',
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-INF-VAX'),
        '呼吸道病毒感染',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'INFECTIOUS_DISEASE'),
        10, 'seed', 'seed'),
    ('PJ-NEU-ASO-01',
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-NEU-ASO'),
        '阿尔茨海默病',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'NEUROSCIENCE'),
        10, 'seed', 'seed')
ON DUPLICATE KEY UPDATE
    program_id                = VALUES(program_id),
    indication_description    = VALUES(indication_description),
    therapeutic_area_id      = VALUES(therapeutic_area_id),
    sort_order               = VALUES(sort_order),
    sys_update_by            = VALUES(sys_update_by);

-- 3) Study（研究）。状态由日期推导：actual_end_date 非空=COMPLETED；actual_start_date 非空=ACTIVE；都为空=PLANNED。
--    阶段编码取自 PipelineConfigManager.PHASES：PRE_IND / IND / PHASE_1 / PHASE_2 / PRE_3 / PHASE_3_1 / PHASE_3_2。
INSERT INTO hd_plt_study (
    study_code, phase_status_code,
    planned_start_date, planned_end_date, actual_start_date, actual_end_date,
    program_id, program_code_snapshot, product_name_snapshot, moa_snapshot,
    source_code_snapshot, origin_code_snapshot,
    project_id, project_code_snapshot,
    therapeutic_area_id, therapeutic_area_code_snapshot, therapeutic_area_name_snapshot,
    indication_description_snapshot, study_description, sys_create_by, sys_update_by)
VALUES
    -- PJ-ONC-ADC-01（肿瘤）：Phase 1 进行中 / Phase 2 进行中 / Phase 3-1 计划中
    ('HDM2001-101', 'PHASE_1', '2025-01-01', '2027-12-31', '2025-03-15', NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-ONC-ADC'),
        'PRG-ONC-ADC', 'HDM2001', 'ADC', 'SELF_DEVELOPED', 'DOMESTIC',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-ONC-ADC-01'), 'PJ-ONC-ADC-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'ONCOLOGY'), 'ONCOLOGY', '肿瘤',
        '晚期实体瘤', 'I 期剂量递增', 'seed', 'seed'),
    ('HDM2001-201', 'PHASE_2', '2025-06-01', '2028-06-30', '2025-09-01', NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-ONC-ADC'),
        'PRG-ONC-ADC', 'HDM2001', 'ADC', 'SELF_DEVELOPED', 'DOMESTIC',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-ONC-ADC-01'), 'PJ-ONC-ADC-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'ONCOLOGY'), 'ONCOLOGY', '肿瘤',
        '晚期实体瘤', 'II 期扩展队列', 'seed', 'seed'),
    ('HDM2001-301', 'PHASE_3_1', '2027-01-01', '2030-12-31', NULL, NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-ONC-ADC'),
        'PRG-ONC-ADC', 'HDM2001', 'ADC', 'SELF_DEVELOPED', 'DOMESTIC',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-ONC-ADC-01'), 'PJ-ONC-ADC-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'ONCOLOGY'), 'ONCOLOGY', '肿瘤',
        '晚期实体瘤', 'III 期准备', 'seed', 'seed'),
    ('HDM2001-302', 'PHASE_3_2', '2028-01-01', '2031-12-31', NULL, NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-ONC-ADC'),
        'PRG-ONC-ADC', 'HDM2001', 'ADC', 'SELF_DEVELOPED', 'DOMESTIC',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-ONC-ADC-01'), 'PJ-ONC-ADC-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'ONCOLOGY'), 'ONCOLOGY', '肿瘤',
        '晚期实体瘤', 'III 期维持', 'seed', 'seed'),
    -- PJ-ONC-ADC-02（肿瘤）：Phase 1 已完成 / PRE-3 进行中
    ('HDM2001-102', 'PHASE_1', '2022-01-01', '2024-12-31', '2022-03-01', '2023-12-31',
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-ONC-ADC'),
        'PRG-ONC-ADC', 'HDM2001', 'ADC', 'SELF_DEVELOPED', 'DOMESTIC',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-ONC-ADC-02'), 'PJ-ONC-ADC-02',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'ONCOLOGY'), 'ONCOLOGY', '肿瘤',
        '三阴性乳腺癌', 'I 期已完成', 'seed', 'seed'),
    ('HDM2001-202', 'PRE_3', '2024-06-01', '2027-06-30', '2024-09-01', NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-ONC-ADC'),
        'PRG-ONC-ADC', 'HDM2001', 'ADC', 'SELF_DEVELOPED', 'DOMESTIC',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-ONC-ADC-02'), 'PJ-ONC-ADC-02',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'ONCOLOGY'), 'ONCOLOGY', '肿瘤',
        '三阴性乳腺癌', 'III 期前桥接', 'seed', 'seed'),
    -- PJ-AUTO-MAB-01（自身免疫）：IND 进行中 / Phase 1 进行中 / Phase 2 计划中
    ('HDM3002-101', 'IND', '2025-02-01', '2026-12-31', '2025-02-15', NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-AUTO-MAB'),
        'PRG-AUTO-MAB', 'HDM3002', 'Monoclonal Antibody', 'IN_LICENSE', 'IMPORTED',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-AUTO-MAB-01'), 'PJ-AUTO-MAB-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'AUTOIMMUNE'), 'AUTOIMMUNE', '自身免疫',
        '系统性红斑狼疮', 'IND 申报', 'seed', 'seed'),
    ('HDM3002-201', 'PHASE_1', '2025-07-01', '2027-06-30', '2025-07-20', NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-AUTO-MAB'),
        'PRG-AUTO-MAB', 'HDM3002', 'Monoclonal Antibody', 'IN_LICENSE', 'IMPORTED',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-AUTO-MAB-01'), 'PJ-AUTO-MAB-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'AUTOIMMUNE'), 'AUTOIMMUNE', '自身免疫',
        '系统性红斑狼疮', 'I 期健康受试者', 'seed', 'seed'),
    ('HDM3002-301', 'PHASE_2', '2026-01-01', '2029-01-31', NULL, NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-AUTO-MAB'),
        'PRG-AUTO-MAB', 'HDM3002', 'Monoclonal Antibody', 'IN_LICENSE', 'IMPORTED',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-AUTO-MAB-01'), 'PJ-AUTO-MAB-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'AUTOIMMUNE'), 'AUTOIMMUNE', '自身免疫',
        '系统性红斑狼疮', 'II 期计划', 'seed', 'seed'),
    -- PJ-MET-PEP-01（代谢与心血管）：PRE-IND 计划中 / Phase 1 进行中 / Phase 2 进行中 / Phase 3-1 已完成
    ('HDM1005-101', 'PRE_IND', '2025-09-01', '2027-09-30', NULL, NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-MET-PEP'),
        'PRG-MET-PEP', 'HDM1005', 'Peptide', 'SELF_DEVELOPED', 'DOMESTIC',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-MET-PEP-01'), 'PJ-MET-PEP-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'METABOLIC_CARDIOVASCULAR'), 'METABOLIC_CARDIOVASCULAR', '代谢与心血管',
        '2 型糖尿病', 'IND 前准备', 'seed', 'seed'),
    ('HDM1005-201', 'PHASE_1', '2024-11-01', '2026-10-31', '2024-11-15', NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-MET-PEP'),
        'PRG-MET-PEP', 'HDM1005', 'Peptide', 'SELF_DEVELOPED', 'DOMESTIC',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-MET-PEP-01'), 'PJ-MET-PEP-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'METABOLIC_CARDIOVASCULAR'), 'METABOLIC_CARDIOVASCULAR', '代谢与心血管',
        '2 型糖尿病', 'I 期耐受性', 'seed', 'seed'),
    ('HDM1005-301', 'PHASE_2', '2025-05-01', '2028-04-30', '2025-05-20', NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-MET-PEP'),
        'PRG-MET-PEP', 'HDM1005', 'Peptide', 'SELF_DEVELOPED', 'DOMESTIC',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-MET-PEP-01'), 'PJ-MET-PEP-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'METABOLIC_CARDIOVASCULAR'), 'METABOLIC_CARDIOVASCULAR', '代谢与心血管',
        '2 型糖尿病', 'II 期疗效', 'seed', 'seed'),
    ('HDM1005-401', 'PHASE_3_1', '2021-01-01', '2023-12-31', '2021-03-01', '2023-06-30',
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-MET-PEP'),
        'PRG-MET-PEP', 'HDM1005', 'Peptide', 'SELF_DEVELOPED', 'DOMESTIC',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-MET-PEP-01'), 'PJ-MET-PEP-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'METABOLIC_CARDIOVASCULAR'), 'METABOLIC_CARDIOVASCULAR', '代谢与心血管',
        '2 型糖尿病', 'III 期已完成', 'seed', 'seed'),
    -- PJ-RES-INH-01（呼吸系统）：Phase 1 进行中 / Phase 2 计划中
    ('HDM4003-101', 'PHASE_1', '2025-04-01', '2027-03-31', '2025-04-15', NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-RES-INH'),
        'PRG-RES-INH', 'HDM4003', 'Small Molecule', 'COOPERATION', 'DOMESTIC',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-RES-INH-01'), 'PJ-RES-INH-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'RESPIRATORY'), 'RESPIRATORY', '呼吸系统',
        '慢性阻塞性肺疾病', 'I 期 PK', 'seed', 'seed'),
    ('HDM4003-201', 'PHASE_2', '2026-03-01', '2029-02-28', NULL, NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-RES-INH'),
        'PRG-RES-INH', 'HDM4003', 'Small Molecule', 'COOPERATION', 'DOMESTIC',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-RES-INH-01'), 'PJ-RES-INH-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'RESPIRATORY'), 'RESPIRATORY', '呼吸系统',
        '慢性阻塞性肺疾病', 'II 期计划', 'seed', 'seed'),
    -- PJ-INF-VAX-01（感染性疾病）：PRE-IND 进行中 / Phase 1 计划中
    ('HDM5001-101', 'PRE_IND', '2025-08-01', '2027-07-31', '2025-08-10', NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-INF-VAX'),
        'PRG-INF-VAX', 'HDM5001', 'Vaccine', 'SELF_DEVELOPED', 'DOMESTIC',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-INF-VAX-01'), 'PJ-INF-VAX-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'INFECTIOUS_DISEASE'), 'INFECTIOUS_DISEASE', '感染性疾病',
        '呼吸道病毒感染', '临床前桥接', 'seed', 'seed'),
    ('HDM5001-201', 'PHASE_1', '2026-06-01', '2028-05-31', NULL, NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-INF-VAX'),
        'PRG-INF-VAX', 'HDM5001', 'Vaccine', 'SELF_DEVELOPED', 'DOMESTIC',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-INF-VAX-01'), 'PJ-INF-VAX-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'INFECTIOUS_DISEASE'), 'INFECTIOUS_DISEASE', '感染性疾病',
        '呼吸道病毒感染', 'I 期计划', 'seed', 'seed'),
    -- PJ-NEU-ASO-01（神经科学）：Phase 1 进行中 / Phase 2 进行中
    ('HDM6001-101', 'PHASE_1', '2025-01-15', '2026-12-31', '2025-02-01', NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-NEU-ASO'),
        'PRG-NEU-ASO', 'HDM6001', 'Antisense Oligonucleotide', 'IN_LICENSE', 'IMPORTED',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-NEU-ASO-01'), 'PJ-NEU-ASO-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'NEUROSCIENCE'), 'NEUROSCIENCE', '神经科学',
        '阿尔茨海默病', 'I 期安全性', 'seed', 'seed'),
    ('HDM6001-201', 'PHASE_2', '2025-10-01', '2028-09-30', '2025-10-15', NULL,
        (SELECT id FROM hd_plt_program WHERE program_code = 'PRG-NEU-ASO'),
        'PRG-NEU-ASO', 'HDM6001', 'Antisense Oligonucleotide', 'IN_LICENSE', 'IMPORTED',
        (SELECT id FROM hd_plt_project WHERE project_code = 'PJ-NEU-ASO-01'), 'PJ-NEU-ASO-01',
        (SELECT id FROM hd_plt_therapeutic_area WHERE area_code = 'NEUROSCIENCE'), 'NEUROSCIENCE', '神经科学',
        '阿尔茨海默病', 'II 期概念验证', 'seed', 'seed')
ON DUPLICATE KEY UPDATE
    phase_status_code              = VALUES(phase_status_code),
    planned_start_date             = VALUES(planned_start_date),
    planned_end_date               = VALUES(planned_end_date),
    actual_start_date              = VALUES(actual_start_date),
    actual_end_date                = VALUES(actual_end_date),
    program_id                     = VALUES(program_id),
    program_code_snapshot          = VALUES(program_code_snapshot),
    product_name_snapshot          = VALUES(product_name_snapshot),
    moa_snapshot                   = VALUES(moa_snapshot),
    source_code_snapshot           = VALUES(source_code_snapshot),
    origin_code_snapshot           = VALUES(origin_code_snapshot),
    project_id                     = VALUES(project_id),
    project_code_snapshot          = VALUES(project_code_snapshot),
    therapeutic_area_id            = VALUES(therapeutic_area_id),
    therapeutic_area_code_snapshot = VALUES(therapeutic_area_code_snapshot),
    therapeutic_area_name_snapshot = VALUES(therapeutic_area_name_snapshot),
    indication_description_snapshot = VALUES(indication_description_snapshot),
    study_description              = VALUES(study_description),
    sys_update_by                  = VALUES(sys_update_by);
